In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
cd '/home/dfried/projects/onecommon/aaai2020/experiments'

/home/dfried/projects/onecommon/aaai2020/experiments


In [3]:
from notebooks.model_sandbox_rel3 import *

freq cutoff: 0
vocab size: 1857
dataset data/onecommon/train_reference_1.txt, total 545056, unks 0, ratio 0.00%
dataset data/onecommon/valid_reference_1.txt, total 69348, unks 202, ratio 0.29%
dataset data/onecommon/test_reference_1.txt, total 67284, unks 210, ratio 0.31%
hits: 0
misses: 4500


100%|██████████████████████████████████████| 8304/8304 [00:22<00:00, 372.00it/s]
/home/dfried/miniconda3/envs/onecommon/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.rnn_reference_model.HierarchicalRnnReferenceModel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/dfried/miniconda3/envs/onecommon/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.ctx_encoder.RelationalAttentionContextEncoder3' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/dfried/miniconda3/envs/onecommon/lib/python3.6/site-packages/t

1: 2 / 1038 	= 0.0019
2: 68 / 1036 	= 0.0656
3: 260 / 968 	= 0.2686
4: 254 / 708 	= 0.3588
5: 214 / 454 	= 0.4714
6: 104 / 240 	= 0.4333
7: 78 / 136 	= 0.5735
8: 28 / 58 	= 0.4828
9: 20 / 30 	= 0.6667
10: 6 / 10 	= 0.6000
11: 4 / 4 	= 1.0000
avg dialogue length: 3.07 turns


/home/dfried/miniconda3/envs/onecommon/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.markable_detector.BiLSTM_CRF' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)


In [4]:
base = 'expts/rel3_tsel_ref_dial_model_separate/directions'
dot_recurrence = 'expts/rel3_tsel_ref_dial_model_separate/dot_recurrence'
dot_recurrence_no_beliefs = 'expts/rel3_tsel_ref_dial_model_separate/dot_recurrence_no-beliefs'
is_selection_old = 'expts/rel3_tsel_ref_dial_model_separate/is_selection_old'
is_selection_dir = 'expts/rel3_tsel_ref_dial_model_separate/is_selection'

# TODO: ep 5 -> ep 20 for with-selection
model_fnames = {
    'basic': f'{base}/base_512_learned-pooling_untied_bidirectional_hidden-mention-encoder/1_ep-30.th',
    'encoder-filtered-shared': f'{base}/base_512_extremes_learned-pooling_untied_bidirectional_hidden-mention-encoder-filtered-shared/1_ep-30.th',
    'encoder-filtered-separate': f'{base}/base_512_extremes_learned-pooling_untied_bidirectional_hidden-mention-encoder-filtered-separate/1_ep-30.th',
    'encoder-filtered-separate-diffs': f'{base}/base_512_extremes_learned-pooling_untied_bidirectional_hidden-mention-encoder-filtered-separate-diffs/1_ep-30.th',
#     'dot-recurrence': f'{dot_recurrence}/base_dr-self+partner-32-mention-selection/1_ep-20.th',
    'dot-recurrence-no-beliefs': f'{dot_recurrence_no_beliefs}/base_mention-selection-ref-partner/1_ep-20.th',
    'dot-recurrence-oracle-no-beliefs': f'{dot_recurrence_no_beliefs}/base_oracle_mention-selection-ref-partner/1_ep-20.th',
#     'dot-recurrence-nm-multi': f'{dot_recurrence}/base_dr-self+partner-64-mention-selection_nmpt-multi-reference_loss-expanded/1_ep-20.th',
    'dot-recurrence-nm-multi-no-beliefs': f'{dot_recurrence_no_beliefs}/base_mention-selection-ref-partner_nmpt-multi_loss-expanded/1_ep-20.th',
    'dot-recurrence-nm-multi-split-count': f'{dot_recurrence_no_beliefs}/base_split_mention-selection-ref-partner_nmpt-multi_loss-expanded_rerun_hce-cf/1_ep-20.th',
    'npm-no-lang_dri-wawm': f'{dot_recurrence_no_beliefs}/base_mention-selection-ref-partner_nmpt-multi_loss-expanded_npm-no-lang_dri-wawm/1_ep-20.th',
#     'with-selection': f'{is_selection_old}/base_hcis_1-layer_dr-in_turn/1_ep-20.th'
#     'with-selection': f'{is_selection_dir}/base_hcis_1-layer_dr-in_turn/1_ep-20.th',
    'is_selection-turn': f'{is_selection_dir}/base_turn/1_ep-7.th',
    'is_selection-turn-dr-in': f'{is_selection_dir}/base_turn/1_ep-4.th',
    'selection-no-lang': f'{dot_recurrence_no_beliefs}/base_mention-selection-ref-partner_nmpt-multi_loss-expanded_sel-no-lang_dri-wawm/1_ep-20.th',
}

In [5]:
models = {
    name: utils.load_model(model_fname, map_location='cpu', prefix_dir=None)
    for name, model_fname in model_fnames.items()
}

In [6]:
# markable_detector = utils.load_model('serialized_models/markable_detector_with_dict_1.th', map_location='cpu', prefix_dir=None)
# markable_detector.eval()
# # TODO: this will no longer be necessary with markable_detector_with_dict
# # markable_corpus = markable_detector.corpus_ty('one_common', 'data/onecommon',
# #                                      train='train_markable_1.txt', valid='valid_markable_1.txt', test='test_markable_1.txt')
# # markable_detector.word_dict = markable_corpus.word_dict

In [7]:
models.keys()

dict_keys(['basic', 'encoder-filtered-shared', 'encoder-filtered-separate', 'encoder-filtered-separate-diffs', 'dot-recurrence-no-beliefs', 'dot-recurrence-oracle-no-beliefs', 'dot-recurrence-nm-multi-no-beliefs', 'dot-recurrence-nm-multi-split-count', 'npm-no-lang_dri-wawm', 'is_selection-turn', 'is_selection-turn-dr-in', 'selection-no-lang'])

In [58]:
# model = models['encoder-filtered-separate-diffs']
# model = models['dot-recurrence']
# model = models['dot-recurrence-no-beliefs']
# model = models['dot-recurrence-nm-multi-no-beliefs']
# model = models['dot-recurrence-nm-multi-split-count']
# model = models['npm-no-lang_dri-wawm']
# model = models['is_selection-turn']
model = models['selection-no-lang']

In [9]:
pdb on

Automatic pdb calling has been turned ON


In [17]:
model.selection_start_emb

Parameter containing:
tensor([-0.0002, -0.0048, -0.0020,  ...,  0.0066, -0.0119,  0.0080],
       requires_grad=True)

In [60]:
agent = RnnAgent(model, args)

In [61]:
class BlankBeliefConstructor(object):
    def make_beliefs(*args):
        return None

In [62]:
blank_belief_constructor = BlankBeliefConstructor()

In [63]:
agent.feed_context(validset[0].ctx.flatten(), blank_belief_constructor)

In [64]:
selection_beliefs.size()

torch.Size([1, 7, 64])

In [65]:
agent.reader_lang_hs

[]

In [66]:
model.selection(agent.state, torch.randn((1, 1, 512*2)), torch.LongTensor([0]), beliefs=selection_beliefs)

(tensor([[-1.0070, -0.3764, -0.7703, -0.8361, -1.3085, -1.2540,  0.1295]],
        grad_fn=<SqueezeBackward1>), None, None)

In [69]:
model.selection(agent.state, torch.randn((1, 1, 512*2)), torch.LongTensor([0]), beliefs=selection_beliefs)[0].sigmoid()

tensor([[0.2676, 0.4070, 0.3164, 0.3024, 0.2127, 0.2220, 0.5323]],
       grad_fn=<SigmoidBackward>)

In [67]:
model.selection(agent.state, torch.randn((1, 1, 512*2)), torch.LongTensor([0]), beliefs=selection_beliefs)

(tensor([[-1.0070, -0.3764, -0.7703, -0.8361, -1.3085, -1.2540,  0.1295]],
        grad_fn=<SqueezeBackward1>), None, None)

In [94]:
def current_sel_prob(agent):
    current_sel_prob = agent.model.selection(
        agent.state, torch.zeros((1, 1, model.args.nhid_lang*2)), torch.LongTensor([0]),
        beliefs=agent.state.make_beliefs(
            'selection', agent.state.turn,  agent.partner_ref_outs + [None], agent.ref_outs + [None]
        )
    )[0].softmax(-1)
    return current_sel_prob

In [95]:
x = torch.zeros(1)

In [119]:
def unsigmoid(x):
    x = x.float()
    return (x / (1 - x)).log()

In [112]:
validset[4].ref_tgt[0].size()

torch.Size([1, 2, 7])

In [114]:
validset[4].num_markables

[tensor([2]), tensor([0])]

In [113]:
validset[4].ref_inpt[0].size()

torch.Size([1, 2, 3])

In [115]:
model.args.dot_recurrence_oracle

False

In [145]:
def selection_rollout(agent, dots_mentioned_per_ref):
    bsz, num_mentions, num_dots = dots_mentioned_per_ref.size()
    assert bsz == 1
    assert num_dots == 7
    
    if num_mentions == 0:
        dummy_ref_inpt = None
        ref_out = None
    else:
        dummy_ref_inpt = torch.zeros(bsz, num_mentions, 3).long()
        ref_out = unsigmoid(dots_mentioned_per_ref), None, None
    num_markables = torch.LongTensor([num_mentions])
    dummy_lang_hs = torch.zeros((bsz, 1, model.args.nhid_lang*2))
    partner_ref_inpt = None
    partner_num_markables = torch.LongTensor([0])
    
    
    # if this is True, should pass dots_mentioned_per_ref for ref_tgt (the second-to-last argument)
    if agent.model.args.dot_recurrence_oracle:
        raise NotImplementedError()
        
    new_ref_outs = agent.ref_outs + [ref_out]
    new_partner_ref_outs = agent.partner_ref_outs + [None]
    
    state = agent.model._update_dot_h_maybe_multi(
        agent.state, torch.zeros((1, 1, model.args.nhid_lang*2)),
        dummy_ref_inpt, partner_ref_inpt,
        num_markables, partner_num_markables,
        ref_out, None,
        None, None
    )
    
    sel_prob = agent.model.selection(
        state, torch.zeros((1, 1, model.args.nhid_lang*2)), torch.LongTensor([0]),
        beliefs=state.make_beliefs(
            'selection', state.turn,  
            # TODO: fix this method so that it takes things in the reasonable order
            new_partner_ref_outs, new_ref_outs
        )
    )[0].softmax(-1)
    return sel_prob

In [68]:
pdb on

Automatic pdb calling has been turned ON


In [144]:
selection_sandbox(0, min_num_mentions=1, mention_marginals=True,
                  ref_marginals=True, for_partner=True, display_mentions=True, datasplit=trainset)

scenario_id: S_7emB6ZKNctXsQbrf
current_sel_prob: tensor([0.1895, 0.1385, 0.0995, 0.1996, 0.1705, 0.0999, 0.1025],
       grad_fn=<ViewBackward>)


to_mention_marginals


to_mention_pred


to_mention_true


beam 0	i have a triangle of dots that are almost black <eos>
greedy	i have a triangle of dots that are almost black <eos>
(tensor([[[inf, inf, -inf, -inf, inf, -inf, -inf]]]), None, None)
pre state_norm: 1.0877209901809692
post state_norm: 8.195716857910156
rollout_sel_prob: tensor([3.6688e-01, 2.7229e-01, 1.1254e-04, 7.5304e-05, 3.6040e-01, 1.1946e-04,
        1.2004e-04], grad_fn=<ViewBackward>)


human	do you have three black dots all close and horizontal . <eos>
detected markables:
{'start': 15, 'end': 31, 'is_self': True, 'text': 'three black dots'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

torch.Size([13, 1, 1024])
current_sel_prob: tensor([3.6043e-01, 2.6901e-01, 1.1331e-04, 7.4455e-05, 3.5529e-01, 1.1811e-04,
        1.4964e-02], grad_fn=<ViewBackward>)


human	THEM: yes , lets select the middle one <eos>
detected markables:
{'start': 21, 'end': 35, 'is_self': True, 'text': 'the middle one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

torch.Size([10, 1, 1024])
current_sel_prob: tensor([3.4550e-01, 2.7857e-01, 3.0809e-04, 1.2712e-04, 3.6529e-01, 3.1781e-04,
        9.8763e-03], grad_fn=<ViewBackward>)


beam 0	ok <selection>
greedy	ok <selection>
None
pre state_norm: 9.386774063110352
post state_norm: 9.386774063110352
rollout_sel_prob: tensor([3.4550e-01, 2.7857e-01, 3.0809e-04, 1.2712e-04, 3.6529e-01, 3.1781e-04,
        9.8763e-03], grad_fn=<ViewBackward>)


human	cool <selection>
detected markables:

----------------------------------------

sel_pred


sel_true


In [139]:
def selection_sandbox(index, datasplit=validset, candidates=1,
                    sample_temperature=0.25, argmax_temperature=0.005,
                    force_num_markables=False,
                    inference='beam', detect_markables=True,
                    min_num_mentions=0, max_num_mentions=12,
                    mention_marginals=False, mention_top_k=None,
                    ref_marginals=False, model=model,
                    for_partner=False, display_mentions=display_mentions
                               ):
    if mention_top_k is not None:
        ap = ArgumentParser()
        PragmaticReferencePredictor.add_args(ap)
        candidate_predictor = PragmaticReferencePredictor(ap.parse_args(['--l1_candidates={}'.format(mention_top_k)]))
    
    if for_partner:
        instance = next(find_same_scenario(index, datasplit=datasplit))
    else:
        instance = datasplit[index]
    
    is_selection_prediction = vars(model.args).get('is_selection_prediction')
    
    ctx, inpts, tgts, ref_inpts, ref_tgts, sel_tgt, \
    [scenario_id], real_ids, partner_real_ids, agents, chat_ids, sel_idxs, \
    lens, rev_idxs, hid_idxs, num_markables, \
    is_self, partner_ref_inpts, partner_ref_tgts_our_view, partner_num_markables,\
    ref_disagreements, partner_ref_disagreements, partner_ref_tgts, is_selections = instance
    print('scenario_id: {}'.format(scenario_id))
    
    bsz = ctx.size(0)
    num_dots = 7
    
    # assume we've been training for a while, so that the beliefs are out of the warmup period (e.g. for models that switch from true->predicted)
    epoch = 1000
    
    dots_mentioned = make_dots_mentioned_multi(ref_tgts, model.args, bsz, num_dots)
    dots_mentioned_per_ref = make_dots_mentioned_per_ref_multi(ref_tgts, model.args, bsz, num_dots)

    partner_dots_mentioned_our_view = make_dots_mentioned_multi(
        partner_ref_tgts_our_view, model.args, bsz, num_dots
    )
    partner_dots_mentioned_our_view_per_ref = make_dots_mentioned_per_ref_multi(
        partner_ref_tgts_our_view, model.args, bsz, num_dots
    )
    
    belief_constructor = BeliefConstructor(
        model.args, epoch, bsz, num_dots, inpts, ref_tgts, partner_ref_tgts_our_view,
        real_ids, partner_real_ids, sel_tgt, is_self,
        partner_dots_mentioned_our_view, partner_dots_mentioned_our_view_per_ref,
        dots_mentioned, dots_mentioned_per_ref,
        ref_inpts, partner_ref_inpts,
        num_markables, partner_num_markables,
    )
    
    blank_belief_constructor = BlankBeliefConstructor()
    
    scenario = all_scenarios[scenario_id]
    agent = RnnAgent(model, args, markable_detector=markable_detector)
    agent.feed_context(ctx.flatten(),
                       belief_constructor,
                       num_markables_to_force=num_markables[0] if force_num_markables else None,
                       min_num_mentions=min_num_mentions,
                       max_num_mentions=max_num_mentions,
                      )
    agent.real_ids = real_ids
    agent.agent_id = agents[0]

    conv = []
    speaker = []
    words_left = 5000

    sentence_ix = 0

    assert len(inpts) == len(tgts)

    while sentence_ix < len(inpts):
        words_og = [corpus.word_dict.idx2word[ix] for ix in inpts[sentence_ix].flatten().numpy()]
        if agent.reader_lang_hs:
            print(agent.reader_lang_hs[-1].size())
            
        assert agent.state.turn == sentence_ix
        current_sel_prob = agent.model.selection(
            agent.state, torch.randn((1, 1, 512*2)), torch.LongTensor([0]),
            beliefs=agent.state.make_beliefs(
                'selection', agent.state.turn,  agent.partner_ref_outs + [None], agent.ref_outs + [None]
            )
        )[0].softmax(-1)
        
        display_attns(scenario, current_sel_prob, agent.agent_id, "current_sel_prob: {}".format(current_sel_prob.flatten()))
        
        if ref_inpts[sentence_ix] is not None:
            dots_mentioned = (ref_tgts[sentence_ix].sum(dim=1) > 0)
            dots_mentioned_per_ref = ref_tgts[sentence_ix]
            this_num_markables = num_markables[sentence_ix]
    #         display_attn(scenario, dots_mentioned.float(), agent.agent_id, name='dots_mentioned')
            mentions = [dots_mentioned_per_ref[:,mention_ix].float()  for mention_ix in range(dots_mentioned_per_ref.size(1))]
            nm_out, _, nm_num_markables = agent.next_mention_outs[-1]
#             print('nm_num_markables: {}'.format(nm_num_markables))
#             print('num_markables: {}'.format(this_num_markables))
            if display_mentions and nm_out is not None:
#                 print(nm_out[0].size())
#                 dummy_targets = torch.zeros_like(nm_out[0].size())
                dummy_targets = torch.zeros((1, nm_num_markables[0].item(), 7)).long()
                _, nm_preds, _ = reference_predictor.forward(
                    True, dummy_targets, nm_out, nm_num_markables
                )
#                 print(nm_preds.size())
                if mention_marginals:
                    display_attns(scenario, nm_out[0].sigmoid().squeeze(1).float(), agent.agent_id, "to_mention_marginals")
                if mention_top_k is not None:
                    cands = candidate_predictor.make_candidates(nm_out, nm_num_markables)[1]
                    for ix in range(cands.size(2)):
                        display_attns(scenario, cands[:,0,ix].float(), agent.agent_id, "to_mention_candidate {}".format(ix))
                display_attns(scenario, nm_preds.squeeze(1).float(), agent.agent_id, "to_mention_pred")
            else:
                print("empty to_mention_pred")
            if display_mentions:
                display_attns(scenario, mentions, agent.agent_id, "to_mention_true")
            
#             for mention_ix in range(dots_mentioned_per_ref.size(1)):
#                 display_attn(scenario, dots_mentioned_per_ref[:,mention_ix].float(), agent.agent_id, name=f'dots_mentioned_{mention_ix}')
        else:
            dots_mentioned = torch.zeros(1, 7).bool()
            dots_mentioned_per_ref = torch.zeros(1, 0, 7).bool()
            this_num_markables = torch.LongTensor([0])
            
        if is_selection_prediction:
            print("predicted is_selection probability")
            print(agent.is_selection_outs[-1].sigmoid())
            print("is_selection: {}".format(is_selections[sentence_ix]))

        if is_self[sentence_ix]:
            if inference == 'sample':
                for sample_ix in range(candidates):
                    pred_outs, _, _, _, extra = agent.model.write(
                        agent.state, 
                        words_left, sample_temperature,
                        dots_mentioned=dots_mentioned,
                        dots_mentioned_per_ref=dots_mentioned_per_ref,
                        num_markables=this_num_markables,
                        is_selection=is_selections[sentence_ix],
                    )
                    print('sample {}\t{}'.format(sample_ix, ' '.join(agent._decode(pred_outs, agent.model.word_dict))))
            elif inference in ['beam', 'gumbel_beam']:
                _, _, decoded = agent.model.write_beam(
                    agent.state, candidates, words_left, 
                    dots_mentioned=dots_mentioned,
                    dots_mentioned_per_ref=dots_mentioned_per_ref,
                    num_markables=this_num_markables,
                    temperature=sample_temperature if inference=='gumbel_beam' else 1.0,
                    gumbel_noise=inference=='gumbel_beam',
                    is_selection=is_selections[sentence_ix],
                )
                for cand_ix, utt in enumerate(decoded):
                    print('beam {}\t{}'.format(cand_ix, ' '.join(utt)))
            else:
                raise NotImplementedError(inference)
            pred_outs, _, _, _, extra = agent.model.write(
                agent.state, 
                words_left, argmax_temperature,
                dots_mentioned=dots_mentioned,
                dots_mentioned_per_ref=dots_mentioned_per_ref,
                num_markables=this_num_markables,
                is_selection=is_selections[sentence_ix],
            )
            print('greedy\t{}'.format(' '.join(agent._decode(pred_outs, agent.model.word_dict))))
    #         print(' '.join(words_og))
    
            rollout_sel_prob = selection_rollout(agent, dots_mentioned_per_ref)
            display_attns(scenario, rollout_sel_prob, agent.agent_id, "rollout_sel_prob: {}".format(rollout_sel_prob.flatten()))

            out = agent.write(
                max_words=words_left,
                force_words=[words_og],
                start_token=words_og[0],
                dots_mentioned=dots_mentioned,
                dots_mentioned_per_ref=dots_mentioned_per_ref,
                num_markables=this_num_markables,
                ref_inpt=ref_inpts[sentence_ix],
                detect_markables=detect_markables,
                is_selection=is_selections[sentence_ix],
#                 min_num_mentions=min_num_mentions,
#                 max_num_mentions=max_num_mentions,
            )
        
        else:
            out = words_og
            agent.read(words_og,
                       dots_mentioned=dots_mentioned,
                       dots_mentioned_per_ref=dots_mentioned_per_ref,
                       num_markables=this_num_markables,
                       partner_ref_inpt=partner_ref_inpts[sentence_ix],
                       partner_num_markables=partner_num_markables[sentence_ix],
                       next_num_markables_to_force=num_markables[sentence_ix + 1] if (force_num_markables and sentence_ix < len(num_markables) - 1) else None,
                       detect_markables=detect_markables,
                       min_num_mentions=min_num_mentions,
                       max_num_mentions=max_num_mentions,
                       is_selection=is_selections[sentence_ix],
                       )
        
#         agent.update_dot_h(ref_inpts[sentence_ix], partner_ref_inpts[sentence_ix],
#                             num_markables[sentence_ix], partner_num_markables[sentence_ix])
            

        print('human\t{}'.format(' '.join(out)))
    
        if is_self[sentence_ix]:
            if detect_markables:
                print('detected markables:')
                for markable in agent.markables[-1]:
                    print(markable)
                this_num_markables_pred = torch.LongTensor([len(agent.markables[-1])])
                this_ref_inpts = agent.ref_inpts[-1]
            elif ref_inpts[sentence_ix] is not None:
                this_num_markables_pred = this_num_markables
                this_ref_inpts = ref_inpt[sentence_ix]
                
                _, ref_preds, ref_stats = reference_predictor.forward(
                    ref_inpts[sentence_ix], ref_tgts[sentence_ix], agent.ref_outs[-1], this_num_markables
                )
            else:
                this_num_markables_pred = None
            if this_num_markables_pred is not None:
                dummy_targets = torch.zeros((1, this_num_markables_pred.item(), 7)).long()
                _, ref_preds, _ = reference_predictor.forward(
                    this_ref_inpts, dummy_targets, agent.ref_outs[-1], this_num_markables_pred
                )
#                 print("ref_preds size:", ref_preds.size())
                if agent.ref_outs[-1] is not None and ref_preds is not None and display_mentions:
                    if ref_marginals:
                        display_attns(scenario, agent.ref_outs[-1][0].sigmoid().squeeze(1), agent.agent_id, "ref_marginal_probs")
                    display_attns(scenario, ref_preds.squeeze(1).float(), agent.agent_id, "refs_pred")
                    display_attns(scenario, ref_tgts[sentence_ix].squeeze(0).float(), agent.agent_id, "refs_true")
#                 print(ref_stats)
            if out[0] != 'YOU':
                utt = ['YOU:'] + out
            else:
                utt = out
        else:
            if detect_markables:
                print('detected markables:')
                for markable in agent.partner_markables[-1]:
                    print(markable)
                this_partner_num_markables_pred = torch.LongTensor([len(agent.partner_markables[-1])])
                this_partner_ref_inpts = agent.partner_ref_inpts[-1]
            elif partner_ref_inpts[sentence_ix] is not None:
                this_partner_num_markables_pred = partner_num_markables[sentence_ix]
                this_partner_ref_inpts = partner_ref_inpts[sentence_ix]
            else:
                this_partner_num_markables_pred = None
            
            if this_partner_num_markables_pred is not None:
#                 _, partner_ref_preds, partner_ref_stats = reference_predictor.forward(
#                     partner_ref_inpts[sentence_ix], partner_ref_tgts_our_view[sentence_ix],
#                     agent.partner_ref_outs[-1], partner_num_markables[sentence_ix]
#                 )
                dummy_targets = torch.zeros((1, this_partner_num_markables_pred.item(), 7)).long()
                _, partner_ref_preds, partner_ref_stats = reference_predictor.forward(
                    this_partner_ref_inpts, dummy_targets,
                    agent.partner_ref_outs[-1], this_partner_num_markables_pred,
                )
    #             print(partner_ref_preds)
                if agent.partner_ref_outs[-1] is not None and partner_ref_preds is not None and display_mentions:
                    if ref_marginals:
                        display_attns(scenario, agent.partner_ref_outs[-1][0].sigmoid().squeeze(1), agent.agent_id, "partner_ref_marginal_probs")
                    display_attns(scenario, partner_ref_preds.squeeze(1).float(), agent.agent_id, "partner_refs_pred")
                    display_attns(scenario, partner_ref_tgts_our_view[sentence_ix].squeeze(0).float(), agent.agent_id, "partner_refs_true")
                    display_attns(scenario, partner_ref_tgts[sentence_ix].squeeze(0).float(), 1 - agent.agent_id, "partner_ref_true (their view)")
#                 print(partner_ref_stats)
            if out[0] == 'THEM:':
                utt = ['YOU:'] + out[1:]
            else:
                utt = ['YOU:'] + out
        
        print()
        print('-'*40)
        print()
        words_left -= len(out)
        conv.append(out)

        if is_selection_function(out):
            # sel_outs should be length 1
            selection_logits, _, _ = agent.sel_outs[-1]
            if display_mentions:
                display_attns(scenario, selection_logits.softmax(-1), agent.agent_id, "sel_pred")
            sel_true = torch.zeros(1,7)
            sel_true[0,sel_tgt] = 1
            if display_mentions:
                display_attns(scenario, sel_true, agent.agent_id, "sel_true")
        sentence_ix += 1

In [72]:
force_contexts_and_mentions(1, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True, datasplit=trainset)

scenario_id: S_xCSFNQ5dYj8dXvkD
human	THEM: i have a small black dot , there is a larger but lighter dot , slightly on left and under it <eos>
detected markables:
{'start': 10, 'end': 27, 'is_self': True, 'text': 'a small black dot'}
{'start': 39, 'end': 63, 'is_self': True, 'text': 'a larger but lighter dot'}
{'start': 93, 'end': 95, 'is_self': True, 'text': 'it'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


beam 0	i have a small light grey dot , and the rest are all of my dots . i have a large dark grey dot with a smaller darker dot to the right of it . they are all the same size <eos>
greedy	i have a small light grey dot , and the rest are all of my dots . i have a large dark grey dot with a smaller darker dot to the right of it . they are all the same size <eos>
human	lonely dark grey dot and a cluster of 6 dots far to the left of it . <unk> the cluster is a small black dot with a large , slightly lighter dot lower to the left <eos>
detected markables:
{'start': 3, 'end': 23, 'is_self': True, 'text': 'lonely dark grey dot'}
{'start': 28, 'end': 47, 'is_self': True, 'text': 'a cluster of 6 dots'}
{'start': 67, 'end': 69, 'is_self': True, 'text': 'it'}
{'start': 78, 'end': 89, 'is_self': True, 'text': 'the cluster'}
{'start': 93, 'end': 110, 'is_self': True, 'text': 'a small black dot'}
{'start': 116, 'end': 146, 'is_self': True, 'text': 'a large , slightly lighter dot'}
ref_marginal_prob

refs_pred


refs_true



----------------------------------------

human	THEM: yes we are talking about the same , wan na select the black small dot ? <eos>
detected markables:
{'start': 53, 'end': 72, 'is_self': True, 'text': 'the black small dot'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


beam 0	yes , let 's pick the black one . <selection>
greedy	yes , let 's pick the black one . <selection>
human	yea , let 's do it <selection>
detected markables:
{'start': 19, 'end': 21, 'is_self': True, 'text': 'it'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [77]:
force_contexts_and_mentions(7, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True)

scenario_id: S_7IaFAblYemWnfpHL
to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
beam 0	i have two small dots very close together . the one on the right is slightly larger and darker <eos>
greedy	i have two small dots very close together . the one on the right is slightly larger and darker <eos>
human	do you see two tiny different <unk> dot beside each other <eos>
detected markables:
{'start': 14, 'end': 42, 'is_self': True, 'text': 'two tiny different <unk> dot'}
{'start': 50, 'end': 60, 'is_self': True, 'text': 'each other'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
human	THEM: haha was about to type that . if the lighter one is slightly below and to the right , click that lighter one . <selection>
detected markables:
{'start': 26, 'end': 30, 'is_self': True, 'text': 'that'}
{'start': 36, 'end': 51, 'is_self': True, 'text': 'the lighter one'}
{'start': 95, 'end': 111, 'is_self': True, 'text': 'that lighter one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

sel_pred


sel_true


In [78]:
force_contexts_and_mentions(9, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True)

scenario_id: S_TJburcYs185be982
to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
beam 0	i have a small black dot with a smaller light gray dot to the left of it <eos>
greedy	i have a small black dot with a smaller light gray dot to the left of it <eos>
human	right in the middle , hello . is there a small black dot ? off to it 's lower left is a tiny dark grey one ? <eos>
detected markables:
{'start': 42, 'end': 59, 'is_self': True, 'text': 'a small black dot'}
{'start': 69, 'end': 74, 'is_self': True, 'text': "it 's"}
{'start': 89, 'end': 109, 'is_self': True, 'text': 'a tiny dark grey one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
human	THEM: yes . pick the black one <selection>
detected markables:
{'start': 14, 'end': 27, 'is_self': True, 'text': 'the black one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

sel_pred


sel_true


In [79]:
force_contexts_and_mentions(11, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True)

scenario_id: S_mCh43je6tDKlCw3Y
to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
beam 0	i have a medium black dot with a smaller light gray dot to its left and slightly below <eos>
greedy	i have a medium black dot with a smaller light gray dot to its left and slightly below <eos>
human	my only black dot has a grey slightly larger dot up and to the right but close to it <eos>
detected markables:
{'start': 3, 'end': 20, 'is_self': True, 'text': 'my only black dot'}
{'start': 25, 'end': 51, 'is_self': True, 'text': 'a grey slightly larger dot'}
{'start': 85, 'end': 87, 'is_self': True, 'text': 'it'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
human	THEM: ok i see it , let 's pick it , the black one <selection>
detected markables:
{'start': 12, 'end': 14, 'is_self': True, 'text': 'it'}
{'start': 29, 'end': 31, 'is_self': True, 'text': 'it'}
{'start': 34, 'end': 47, 'is_self': True, 'text': 'the black one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

sel_pred


sel_true


In [68]:
force_contexts_and_mentions(9, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=False)

scenario_id: S_TJburcYs185be982
predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
human	THEM: right in the middle , hello . is there a small black dot ? off to it 's lower left is a tiny dark grey one ? <eos>
detected markables:
{'start': 42, 'end': 59, 'is_self': True, 'text': 'a small black dot'}
{'start': 69, 'end': 74, 'is_self': True, 'text': "it 's"}
{'start': 89, 'end': 109, 'is_self': True, 'text': 'a tiny dark grey one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
beam 0	yes , let 's pick the black one <eos>
greedy	yes , let 's pick the black one <eos>
human	yes . pick the black one <selection>
detected markables:
{'start': 14, 'end': 27, 'is_self': True, 'text': 'the black one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [69]:
force_contexts_and_mentions(13, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True)

scenario_id: S_HipCMaYBA70VTN6W
predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
human	THEM: do you see 3 dots in an almost vertical line ? top and bottom dark middle one light ? <eos>
detected markables:
{'start': 14, 'end': 20, 'is_self': True, 'text': '3 dots'}
{'start': 50, 'end': 53, 'is_self': True, 'text': 'top'}
{'start': 58, 'end': 80, 'is_self': True, 'text': 'bottom dark middle one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
beam 0	i have a cluster of 3 dots . the one on the left is the darkest <eos>
greedy	i have a cluster of 3 dots . the one on the left is the darkest <eos>
human	yeah . i have that too . choose the middle one ! <selection>
detected markables:
{'start': 17, 'end': 21, 'is_self': True, 'text': 'that'}
{'start': 35, 'end': 49, 'is_self': True, 'text': 'the middle one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [70]:
force_contexts_and_mentions(6, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=False)

scenario_id: S_pzxf1Jvm2dMsyamY
predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
human	THEM: i have four in a clustered line . the one on the far right is highest , small and very dark . the two in the middle are largest <eos>
detected markables:
{'start': 10, 'end': 14, 'is_self': True, 'text': 'four'}
{'start': 37, 'end': 44, 'is_self': True, 'text': 'the one'}
{'start': 97, 'end': 104, 'is_self': True, 'text': 'the two'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
beam 0	i have a small light gray dot with a smaller dark gray dot to the left of it <eos>
greedy	i have a small light gray dot in the middle of the rest . the rest are light grey . <eos>
human	yes is the one all the way left slightly above the rest ? if so click that lightest highest one <selection>
detected markables:
{'start': 10, 'end': 17, 'is_self': True, 'text': 'the one'}
{'start': 50, 'end': 58, 'is_self': True, 'text': 'the rest'}
{'start': 73, 'end': 98, 'is_self': True, 'text': 'that lightest highest one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [71]:
force_contexts_and_mentions(9, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=False)

scenario_id: S_TJburcYs185be982
predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
human	THEM: right in the middle , hello . is there a small black dot ? off to it 's lower left is a tiny dark grey one ? <eos>
detected markables:
{'start': 42, 'end': 59, 'is_self': True, 'text': 'a small black dot'}
{'start': 69, 'end': 74, 'is_self': True, 'text': "it 's"}
{'start': 89, 'end': 109, 'is_self': True, 'text': 'a tiny dark grey one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
beam 0	yes , let 's pick the black one <eos>
greedy	yes , let 's pick the black one <eos>
human	yes . pick the black one <selection>
detected markables:
{'start': 14, 'end': 27, 'is_self': True, 'text': 'the black one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [74]:
force_contexts_and_mentions(12, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=True)

scenario_id: S_E7MSFcjSEz7kyXfJ
predicted is_selection probability
tensor([0.0101], grad_fn=<SigmoidBackward>)
is_selection: tensor([False])
human	THEM: large black one with a very light smaller one to it 's upper right ? <eos>
detected markables:
{'start': 3, 'end': 18, 'is_self': True, 'text': 'large black one'}
{'start': 24, 'end': 48, 'is_self': True, 'text': 'a very light smaller one'}
{'start': 52, 'end': 57, 'is_self': True, 'text': "it 's"}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


predicted is_selection probability
tensor([0.0484], grad_fn=<SigmoidBackward>)
is_selection: tensor([True])
beam 0	yes , let 's pick the black one <eos>
greedy	yes , let 's pick the black one <eos>
human	yes good description ! click the dark one ! <selection>
detected markables:
{'start': 32, 'end': 44, 'is_self': True, 'text': 'the dark one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [68]:
force_contexts_and_mentions(3, min_num_mentions=1, mention_marginals=True,
                            ref_marginals=True, for_partner=False)

scenario_id: S_kyf7CjNdkIqHi5pb
human	THEM: 2 dark gray dots very close to each other , the one on the right is smaller than the left one <eos>
detected markables:
{'start': 3, 'end': 19, 'is_self': True, 'text': '2 dark gray dots'}
{'start': 34, 'end': 44, 'is_self': True, 'text': 'each other'}
{'start': 47, 'end': 54, 'is_self': True, 'text': 'the one'}
{'start': 84, 'end': 96, 'is_self': True, 'text': 'the left one'}
partner_ref_marginal_probs


partner_refs_pred


partner_refs_true


partner_ref_true (their view)



----------------------------------------

to_mention_marginals


to_mention_pred


to_mention_true


beam 0	yes , the one on the right is slightly larger and slightly lighter ? <eos>
greedy	yes , the one on the right is slightly larger and slightly lighter ? <eos>
human	let 's select the smaller one on the right <selection>
detected markables:
{'start': 17, 'end': 32, 'is_self': True, 'text': 'the smaller one'}
ref_marginal_probs


refs_pred


refs_true



----------------------------------------

sel_pred


sel_true


In [58]:
import json
from utils import ContextGenerator

In [43]:
ctx_gen = ContextGenerator('data/onecommon/shared_4.txt')

In [44]:
with open('data/onecommon/shared_4.json', "r") as f:
    scenario_list = json.load(f)
selfplay_scenarios = {scenario['uuid']: scenario for scenario in scenario_list}

In [45]:
scenario = None
for ix, ([scenario_id], (ctx1, ctx2), (ids1, ids2)) in enumerate(ctx_gen.iter()):
#     if scenario_id == 'S_11J8n40u4HRVduwi':
#         print('found it')
#         scenario = scenarios[scenario_id]
#         break
    if ix == 2:
        scenario = selfplay_scenarios[scenario_id]
        print(scenario_id)
        break

S_xM5bXi3lMqXHKKgP


In [46]:
import random

In [ ]:
# selfplay emulation
scenario = selfplay_scenarios[scenario_id]
for agent, agent_id, ctx, real_ids in zip([alice, bob], [0, 1], [ctx1, ctx2], [ids1, ids2]):
    agent.feed_context(ctx)
    agent.real_ids = real_ids
    agent.agent_id = agent_id
    
dot_mention_samples = 1
utt_samples = 10
    
writer, reader = [alice, bob]
conv = []
speaker = []
words_left = 5000

num_mentions = 2
num_dots_to_mention = 3

sample_temperature = 0.25
argmax_temperature = 0.005

def make_dots_mentioned_per_ref():
#     # fixed
#     return torch.BoolTensor([[1,1,0,0,0,0,0], [1,0,0,0,0,0,0]]).unsqueeze(0)
#     return torch.BoolTensor([[1,1,0,0,0,0,0]]).unsqueeze(0)

    # random initial and drop
    mentioned = torch.zeros(1,num_mentions,7).bool()
    dots_mentioned = []
    for _ in range(num_dots_to_mention):
        dot_ix = torch.randint(7, (1,))
        mentioned[:,0,dot_ix] = 1
        dots_mentioned.append(dot_ix)
        
    for mention_ix in range(1, num_mentions):
        mentioned[:,mention_ix,random.choice(dots_mentioned)] = 1
    return mentioned
    

    # random 
#     mentioned = torch.zeros(1,num_mentions,7).bool()
#     for mention_ix in range(num_mentions):
#         for _ in range(num_dots_to_mention):
#             dot_ix = torch.randint(7, (1,))
#             mentioned[:,mention_ix,dot_ix] = 1
#     return mentioned

display_context = True

while True:
    dots_mentioned_per_ref = make_dots_mentioned_per_ref()
    dots_mentioned = dots_mentioned_per_ref.max(1).values
    
    num_markables=torch.LongTensor([dots_mentioned_per_ref.size(1)])
    if display_context:
        for mention_ix in range(dots_mentioned_per_ref.size(1)):
            display_attn(scenario, dots_mentioned_per_ref[:,mention_ix].float(), writer.agent_id, name=f'dots_mentioned_{mention_ix}')
    for us in range(utt_samples):
        outs, _, _, _, extra = writer.model.write(
            writer.ctx,
            writer.ctx_differences,
            writer.ctx_h,
            writer.reader_and_writer_lang_h,
            words_left,
            sample_temperature,
            dots_mentioned=dots_mentioned,
            dots_mentioned_per_ref=dots_mentioned_per_ref,
            num_markables=num_markables,
        )
        print('agent {}; sample {}\t{}'.format(writer.agent_id, us, ' '.join(writer._decode(outs, writer.model.word_dict))))
    print()
        
    num_markables=torch.LongTensor([num_mentions])
    if display_context:
        for mention_ix in range(dots_mentioned_per_ref.size(1)):
            display_attn(scenario, dots_mentioned_per_ref[:,mention_ix].float(), writer.agent_id, name=f'dots_mentioned_{mention_ix}')
    out = writer.write(
        max_words=words_left,
        dots_mentioned=dots_mentioned,
        dots_mentioned_per_ref=dots_mentioned_per_ref,
        num_markables=num_markables,
        temperature_override=argmax_temperature,
    )
    print('agent {}; argmax\t{}'.format(writer.agent_id, ' '.join(out)))
    print()
    
#     if display_context and writer.extras[-1].get('feed_ctx_attn_prob', None) is not None:
#         display_attn(scenario, writer.extras[-1]['feed_ctx_attn_prob'], writer.agent_id, name='feed attention')
    
#     if display_context and writer.extras[-1].get('word_ctx_attn_prob_mean', None) is not None:
#         display_attn(scenario, writer.extras[-1]['word_ctx_attn_prob_mean'], writer.agent_id, name='word attention mean')
        
#     for ix, ix_attn in enumerate(writer.extras[-1]['word_ctx_attn_probs']):
#         display_attn(scenario, ix_attn, writer.agent_id, name='t {}: {}'.format(ix, out[ix]))
        
    print('{}\t{}'.format(writer.agent_id, ' '.join(out)))
    print('-'*60)
        
    words_left -= len(out)
    conv.append(out)
    speaker.append(writer.agent_id)
    reader.read(out)
    if is_selection(out) or words_left <= 1:
        break
    writer, reader = reader, writer

NameError: name 'selfplay_scenarios' is not defined

> <ipython-input-41-e274016a0281>(2)<module>()
      1 # selfplay emulation
----> 2 scenario = selfplay_scenarios[scenario_id]
      3 for agent, agent_id, ctx, real_ids in zip([alice, bob], [0, 1], [ctx1, ctx2], [ids1, ids2]):
      4     agent.feed_context(ctx)
      5     agent.real_ids = real_ids

--KeyboardInterrupt--


In [ ]:
markable_detector = utils.load_model('')

In [92]:
model.args.mark_dots_mentioned

True

In [94]:
validset[0]._asdict().keys()

odict_keys(['ctx', 'inpts', 'tgts', 'ref_inpt', 'ref_tgt', 'sel_tgt', 'scenario_ids', 'real_ids', 'partner_real_ids', 'agents', 'chat_ids', 'sel_idxs', 'lens', 'rev_idxs', 'hid_idxs', 'num_markables', 'is_self', 'partner_ref_inpt', 'partner_ref_tgt_our_view', 'partner_num_markables', 'referent_disagreements', 'partner_referent_disagreements'])

In [102]:
ctx.size()

torch.Size([1, 28])

In [75]:
def selfplay_contexts_and_mentions(scenario, candidates=1,
                                    sample_temperature=0.25, argmax_temperature=0.005,
                                    inference='beam'):
#     scenario = selfplay_scenarios[scenario_id]
    alice = RnnAgent(model, args)
    bob = RnnAgent(model, args)
    
    for agent, agent_id, ctx, real_ids in zip([alice, bob], [0, 1], [ctx1, ctx2], [ids1, ids2]):
        agent.feed_context(ctx)
        agent.real_ids = real_ids
        agent.agent_id = agent_id
#     ctx, inpts, tgts, ref_inpts, ref_tgts, sel_tgt, \
#     [scenario_id], real_ids, partner_real_ids, agents, chat_ids, sel_idxs, \
#     lens, rev_idxs, hid_idxs, num_markables, \
#     is_self, partner_ref_inpts, partner_ref_tgts_our_view, partner_num_markables,\
#     ref_disagreements, partner_ref_disagreements = datasplit[index]
    
    bsz = 1
    num_dots = 7
    
    # assume we've been training for a while, so that the beliefs are out of the warmup period (e.g. for models that switch from true->predicted)
    epoch = 1000
    
    assert [] == model.args.ref_beliefs == model.args.partner_ref_beliefs == model.args.generation_beliefs == model.args.selection_beliefs == model.args.next_mention_beliefs
    
    belief_constructor = BlankBeliefConstructor()
    
    writer, reader = alice, bob
    
    conv = []
    speaker = []
    words_left = 5000

    sentence_ix = 0
    
    while words_left > 0:
        
        nm_out, _, nm_num_markables = agent.next_mention_outs[-1]
        if display_mentions and nm_out is not None:
            dummy_targets = torch.zeros((1, nm_num_markables[0].item(), 7)).long()
            _, nm_preds, _ = reference_predictor.forward(
                True, dummy_targets, nm_out, nm_num_markables
            )
            display_attns(scenario, nm_preds.squeeze(1).float(), agent.agent_id, "to_mention_pred")
        else:
            print("empty to_mention_pred")
        display_attns(scenario, mentions, agent.agent_id, "to_mention_true")
#             for mention_ix in range(dots_mentioned_per_ref.size(1)):
#                 display_attn(scenario, dots_mentioned_per_ref[:,mention_ix].float(), agent.agent_id, name=f'dots_mentioned_{mention_ix}')
        else:
            dots_mentioned = torch.zeros(1, 7).bool()
            dots_mentioned_per_ref = torch.zeros(1, 0, 7).bool()
            this_num_markables = torch.LongTensor([0])

        if is_self[sentence_ix]:
            if inference == 'sample':
                for sample_ix in range(candidates):
                    pred_outs, _, _, _, extra = agent.model.write(
                        agent.state, 
                        words_left, sample_temperature,
                        dots_mentioned=dots_mentioned,
                        dots_mentioned_per_ref=dots_mentioned_per_ref,
                        num_markables=this_num_markables
                    )
                    print('sample {}\t{}'.format(sample_ix, ' '.join(agent._decode(pred_outs, agent.model.word_dict))))
            elif inference in ['beam', 'gumbel_beam']:
                _, _, decoded = agent.model.write_beam(
                    agent.state, candidates, words_left, 
                    dots_mentioned=dots_mentioned,
                    dots_mentioned_per_ref=dots_mentioned_per_ref,
                    num_markables=this_num_markables,
                    temperature=sample_temperature if inference=='gumbel_beam' else 1.0,
                    gumbel_noise=inference=='gumbel_beam',
                )
                for cand_ix, utt in enumerate(decoded):
                    print('beam {}\t{}'.format(cand_ix, ' '.join(utt)))
            else:
                raise NotImplementedError(inference)
            pred_outs, _, _, _, extra = agent.model.write(
                agent.state, 
                words_left, argmax_temperature,
                dots_mentioned=dots_mentioned,
                dots_mentioned_per_ref=dots_mentioned_per_ref,
                num_markables=this_num_markables
            )
            print('greedy\t{}'.format(' '.join(agent._decode(pred_outs, agent.model.word_dict))))
    #         print(' '.join(words_og))

            out = agent.write(
                max_words=words_left,
                force_words=[words_og],
                start_token=words_og[0],
                dots_mentioned=dots_mentioned,
                dots_mentioned_per_ref=dots_mentioned_per_ref,
                num_markables=this_num_markables,
                ref_inpt=ref_inpts[sentence_ix],
                detect_markables=detect_markables,
            )
        
        else:
            out = words_og
            agent.read(words_og,
                       dots_mentioned=dots_mentioned,
                       dots_mentioned_per_ref=dots_mentioned_per_ref,
                       num_markables=this_num_markables,
                       partner_ref_inpt=partner_ref_inpts[sentence_ix],
                       partner_num_markables=partner_num_markables[sentence_ix],
                       next_num_markables_to_force=num_markables[sentence_ix + 1] if (force_num_markables and sentence_ix < len(num_markables) - 1) else None,
                       detect_markables=detect_markables,
                       )
        
#         agent.update_dot_h(ref_inpts[sentence_ix], partner_ref_inpts[sentence_ix],
#                             num_markables[sentence_ix], partner_num_markables[sentence_ix])
            

        print('human\t{}'.format(' '.join(out)))
    
        if is_self[sentence_ix]:
            if detect_markables:
                print('detected markables:')
                for markable in writer.markables[-1]:
                    print(markable)
                this_num_markables_pred = torch.LongTensor([len(writer.markables[-1])])
                this_ref_inpts = writer.ref_inpts[-1]
            elif ref_inpts[sentence_ix] is not None:
                this_num_markables_pred = this_num_markables
                this_ref_inpts = ref_inpt[sentence_ix]
                
                _, ref_preds, ref_stats = reference_predictor.forward(
                    ref_inpts[sentence_ix], ref_tgts[sentence_ix], writer.ref_outs[-1], this_num_markables
                )
            else:
                this_num_markables_pred = None
            if this_num_markables_pred is not None:
                dummy_targets = torch.zeros((1, this_num_markables_pred.item(), 7)).long()
                _, ref_preds, _ = reference_predictor.forward(
                    this_ref_inpts, dummy_targets, writer.ref_outs[-1], this_num_markables_pred
                )
#                 print("ref_preds size:", ref_preds.size())
                if writer.ref_outs[-1] is not None and ref_preds is not None:
                    display_attns(scenario, writer.ref_outs[-1][0].sigmoid().squeeze(1), writer.agent_id, "ref_marginal_probs")
                    display_attns(scenario, ref_preds.squeeze(1).float(), writer.agent_id, "refs_pred")
                    display_attns(scenario, ref_tgts[sentence_ix].squeeze(0).float(), writer.agent_id, "refs_true")
#                 print(ref_stats)
            if out[0] != 'YOU':
                utt = ['YOU:'] + out
            else:
                utt = out
        else:
            if detect_markables:
                print('detected markables:')
                for markable in writer.partner_markables[-1]:
                    print(markable)
                this_partner_num_markables_pred = torch.LongTensor([len(writer.partner_markables[-1])])
                this_partner_ref_inpts = writer.partner_ref_inpts[-1]
            elif partner_ref_inpts[sentence_ix] is not None:
                this_partner_num_markables_pred = partner_num_markables[sentence_ix]
                this_partner_ref_inpts = partner_ref_inpts[sentence_ix]
            else:
                this_partner_num_markables_pred = None
            
            if this_partner_num_markables_pred is not None:
#                 _, partner_ref_preds, partner_ref_stats = reference_predictor.forward(
#                     partner_ref_inpts[sentence_ix], partner_ref_tgts_our_view[sentence_ix],
#                     writer.partner_ref_outs[-1], partner_num_markables[sentence_ix]
#                 )
                dummy_targets = torch.zeros((1, this_partner_num_markables_pred.item(), 7)).long()
                _, partner_ref_preds, partner_ref_stats = reference_predictor.forward(
                    this_partner_ref_inpts, dummy_targets,
                    writer.partner_ref_outs[-1], this_partner_num_markables_pred,
                )
    #             print(partner_ref_preds)
                if writer.partner_ref_outs[-1] is not None and partner_ref_preds is not None:
                    display_attns(scenario, writer.partner_ref_outs[-1][0].sigmoid().squeeze(1), writer.agent_id, "partner_ref_marginal_probs")
                    display_attns(scenario, partner_ref_preds.squeeze(1).float(), writer.agent_id, "partner_refs_pred")
                    display_attns(scenario, partner_ref_tgts_our_view[sentence_ix].squeeze(0).float(), writer.agent_id, "partner_refs_true")
                    display_attns(scenario, partner_ref_tgts[sentence_ix].squeeze(0).float(), 1 - writer.agent_id, "partner_ref_true (their view)")
#                 print(partner_ref_stats)
            if out[0] == 'THEM:':
                utt = ['YOU:'] + out[1:]
            else:
                utt = ['YOU:'] + out
        
        print()
        print('-'*40)
        print()
        words_left -= len(out)
        conv.append(out)
        
        if is_selection(out):
            # sel_outs should be length 1
            selection_logits, _, _ = writer.sel_outs[-1]
            display_attns(scenario, selection_logits.sigmoid().float(), writer.agent_id, "sel_pred")
            sel_true = torch.zeros(1,7)
            sel_true[0,sel_tgt] = 1
            display_attns(scenario, sel_true, writer.agent_id, "sel_true")
            break
            
        writer, reader = reader, writer

        sentence_ix += 1